import 'package:design_system/design_system.dart';
import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

import 'addons/theme_studio_addon.dart';
// Generated by widgetbook_generator (melos run gen) from every
// @widgetbook.UseCase-annotated function under lib/use_cases/.
import 'main.directories.g.dart';

void main() {
  runApp(const DesignSystemWidgetbookApp());
}

@widgetbook.App()
class DesignSystemWidgetbookApp extends StatelessWidget {
  const DesignSystemWidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      directories: directories,
      addons: [
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(name: 'Light', data: AppTheme.light()),
            WidgetbookTheme(name: 'Dark', data: AppTheme.dark()),
          ],
        ),
        // Must come after MaterialThemeAddon -- addons nest in list order
        // (first = outermost), and this one reads the brightness that
        // addon already selected (see theme_studio_addon.dart).
        ThemeStudioAddon(),
      ],
    );
  }
}
