/// {{feature_name.titleCase()}} feature (§5) — generated by `mason make
/// feature` as the minimal proven slice (ADR-009). UseCases and local
/// caching are manual additions when justified (§21, §11).
library;

export 'src/data/datasources/{{feature_name.snakeCase()}}_remote_datasource.dart';
export 'src/data/models/{{feature_name.snakeCase()}}_model.dart';
export 'src/data/repositories/{{feature_name.snakeCase()}}_repository_impl.dart';
export 'src/domain/entities/{{feature_name.snakeCase()}}.dart';
export 'src/domain/repositories/{{feature_name.snakeCase()}}_repository.dart';
export 'src/presentation/cubit/{{feature_name.snakeCase()}}_cubit.dart';
export 'src/presentation/cubit/{{feature_name.snakeCase()}}_state.dart';
export 'src/presentation/pages/{{feature_name.snakeCase()}}_page.dart';
